#######################################################
# Check dockerhub for updates to the tomcat container #
#######################################################

name: Check For Upstream Updates

on:
  schedule:
    # Once a day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  createMatrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create matrix
        id: set-matrix
        run: |
          matrix=$(
          echo {\
            $(.github/helperScripts/remoteBranchNamesToJSON.sh)", "\
            $(.github/helperScripts/tomcatVersions.sh)", "\
            $(.github/helperScripts/jdkVersions.sh)\
          }\
          )
          echo $matrix
          echo "::set-output name=matrix::$matrix"

  verifyMatrix:
    runs-on: ubuntu-latest
    needs: createMatrix
    steps:
      - name: Verify matrix
        run: |
          matrix='${{ needs.createMatrix.outputs.matrix }}'
          echo $matrix

  checkUpstream:
    runs-on: ubuntu-latest
    needs: createMatrix
    strategy:
      matrix: ${{ fromJson(needs.createMatrix.outputs.matrix) }}

    steps:

    - name: Set environment variables
      run: |
        echo "scriptsdir=.github/helperScripts" >> $GITHUB_ENV

    - name: Checkout default branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Verify repo has been cloned
      run: |
        git status
        git branch -a
        git remote -v

    - name: Check matrix outputs
      run: |
        echo "Branch: ${{ matrix.branch }} Tomcat: ${{ matrix.tomcat }} JDK: ${{ matrix.jdk }}"

    - name: Grab the most recent upstream tomcat version
      run: |
        upstream=$( ${{ env.scriptsdir }}/dockertags.sh tomcat | ${{ env.scriptsdir }}/findTomcatVersion.sh ${{matrix.tomcat}} ${{ matrix.jdk }})
        echo $upstream
        echo "upstream=$upstream" >> $GITHUB_ENV

    - name: Check if up to date
      run: |
        echo Latest upstream version: ${{ env.upstream }}
        git branch --list -r "origin/${{ matrix.tomcat }}.*-jdk${{ matrix.jdk }}-openjdk" | head -c1 | wc -c
        test $(git branch --list -r "origin/${{ matrix.tomcat }}.*-jdk${{ matrix.jdk }}-openjdk" | head -c1 | wc -c) -ne 0 &&
        up2date=true || up2date=false
        echo "Up to date with latest version (${{ env.upstream }})?"
        echo $up2date
        echo "up2date=$up2date" >> $GITHUB_ENV

    #- name: Does most recent version exist
    #  run: |
    #    echo ${{ env.upstream }}
    #    git branch -a
    #    git branch -a | grep "${{ env.upstream }}" &&
    #    echo "Already up to date with Tomcat ${{ env.upstream }}" ||
    #    {
    #    echo "New Tomcat version ${{ env.upstream }}"
    #    git branch -r | ${{ scriptsdir }}/findTomcatVersion.sh ${{ matrix.tomcat }} ${{ matrix.jdk }} 
    #    echo "Psuedocode: Find most up to date tomcat version ${{ matrix.tomcat }} with jdk version ${{ matrix.jdk }}" &&
    #    echo "Psuedocode: Branch off of most recent version in repo"

    - name: Already up to date
      if: ${{ env.up2date == true}}
      run: |
        echo "Already up to date with upstream: ${{ env.upstream }}"

    - name: Checkout branch
      if: ${{ env.up2date != true }}
      run: |
        echo "tag=${{ env.upstream }}" >> $GITHUB_ENV
        echo "New upstream version ${{ env.upstream }}"
        current=$(git branch -r --list "origin/${{ matrix.tomcat }}.*-jdk${{ matrix.jdk }}-openjdk" | sort -Vr | head -n1)
        test -n "$current" && { echo "Most recent unidata/tomcat version found at: $current"; branch=$current; } ||
        { echo "No local branch found with tomcat ${{ matrix.tomcat }} and JDK ${{ matrix.jdk }}; branch="latest"; }
        echo "Creating new branch from $branch ..."
        git checkout -b ${{ env.upstream }} $branch

    - name: Update Dockerfile
      if: ${{ env.up2date != 'true' }}
      run: |
        sed -e "s/FROM tomcat:.*/FROM tomcat:${{ env.upstream }}/g" Dockerfile -i
        grep "FROM tomcat:" Dockerfile

    - name: Commit and push changes
      run: echo "Commit and push changes"
